#!/usr/bin/sh

# Discord Rich Presence
for i in {0..9}; do
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.DiscordCanary,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
done

/app/bin/xivlauncher "$@"